---

#####################
# Install Python
#####################

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install Python
      yum:
        name: python
        state: present


#######################
# Setup K8s components
#######################

- hosts: etcd
  roles:
    - common
    - etcd

- hosts: controller
  roles:
    - common
    - controller

- hosts: worker
  roles:
    - common
    - worker
